services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_SERVER: postgres
      DATABASE_PORT: 5432
      RABBITMQ_HOST: rabbitmq_shortener
      RABBITMQ_PORT: 5672
      REDIS_HOST: redis_shortener
      REDIS_PORT: 6379
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/migrations:/app/backend/migrations
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python src/brokers/consumer.py
    env_file:
      - .env
    environment:
      DATABASE_SERVER: postgres
      DATABASE_PORT: 5432
      RABBITMQ_HOST: rabbitmq_shortener
      RABBITMQ_PORT: 5672
      REDIS_HOST: redis_shortener
      REDIS_PORT: 6379
    volumes:
      - ./backend/src:/app/backend/src
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: frontend_shortener
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro


  postgres:
    image: postgres:16-alpine
    container_name: postgres_shortener
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis_shortener
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_shortener
    hostname: rabbitmq_shortener
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 1431655766
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
