[project]
name = "url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=10.0.1",
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "mypy>=2.3.0",
    "passlib[bcrypt]>=1.7.4",
    "pwdlib[bcrypt]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-multipart>=0.0.32",
    "redis>=5.0.0",
    "ruff>=0.16.0",
    "setuptools>=83.0.0",
    "sqids>=0.5.2",
    "sqlmodel>=0.0.39",
    "testcontainers[postgres]>=4.15.0",
    "user-agents>=2.2.0",
    "uvicorn[standard]>=0.52.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
